title: Page hosted by Github
author: Alexey Khrushch
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Multiline:
  1
  2
  3

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
